### ISSUE TITLE
Differences in DataCatalog identifier presentation

### ISSUE THREAD

**Issue by AlasdairGray** [HW-SWeL/Scraper#27]
I was showing @Drosophilic the BKGExplorer this morning and he picked up that FAIRsharing has a strange looking identifier 'https://bioschemas.org/crawl/v1/10008/fairsharing.org/2138977099' instead of others like Guide to Pharmacology that are of the form 'http://www.guidetopharmacology.org'. Looking at the underlying markup of these two resources, it is not immediately obvious to me why they are different.

**Comment by kcmcleod** [comment]
I agree the published identifier is wrong. It is using one of our generated ids that we deploy when we can't find an @ id.
When I tried to rescrape the page today, this issue was already fixed. I tried 10 times and each time it used the @ id of the source page (ie https://fairsharing.org/).

However, as the markup uses identifier, should I use that property value instead?
